# SLDSMART Configuration

# Database settings
database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "sldsmart"

# Discord bot settings
discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  guild_id: "YOUR_DISCORD_GUILD_ID"

# Currency symbol
currency_symbol: "$"

# Marketplace settings
marketplace:
  listing_fee: 10
  admin_listing_fee: 5
  max_price: 1000000
  min_price: 1

# Discord link settings
discord_link:
  expiration_minutes: 5

# Debug mode (set to true for additional logging)
debug: false