name: SLDSMART
version: '${project.version}'
main: org.slmarket.sLDSMART.SLDSMART
api-version: '1.16'
authors: [YourName]
description: A marketplace plugin with Discord integration
commands:
  marketplace:
    description: Open the marketplace GUI
    usage: /<command>
  marketplaceadmin:
    description: Admin commands for the marketplace
    usage: /<command> <add|remove> [price]
    permission: sldsmart.admin
  linkdiscord:
    description: Link your Minecraft account to Discord
    usage: /<command>
permissions:
  sldsmart.admin:
    description: Allows access to admin commands
    default: op
  sldsmart.use:
    description: Allows use of the marketplace
    default: true